version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/home/filebeat/logs
    links:
      - logstash